name: Test Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows
      - action.yml
      - hello.py
  push:
    branches:
      - main
    paths:
      - .github/workflows
      - action.yml
      - hello.py

jobs:
  TestAction:
    name: Test Action
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run Action
        uses: ./
